version: "2"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - dupl
    - dupword
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - gocheckcompilerdirectives
    - gocritic
    # - godoclint
    # - godot
    - godox
    - gosec
    - gosmopolitan
    - govet
    - iface
    - importas
    - ineffassign
    - intrange
    - mirror
    - misspell
    - modernize
    - musttag
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - predeclared
    - protogetter
    - recvcheck
    - revive
    - sloglint
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    # - wrapcheck

  exclusions:
    rules:
      - linters:
          - errcheck
        source: "defer .*Close()"

  settings:
    errcheck:
      check-type-assertions: true
    godot:
      scope: all
      capital: true
    iface:
      enable:
        - identical
        - unused
        - unexported
    importas:
      no-extra-aliases: true
      alias:
        - pkg: github.com/tzrikka/revchat/pkg/bitbucket/activities
          alias: bitbucket
        - pkg: github.com/tzrikka/revchat/pkg/bitbucket/workflows
          alias: bitbucketwf
        - pkg: github.com/tzrikka/revchat/pkg/github/activities
          alias: github
        - pkg: github.com/tzrikka/revchat/pkg/github/workflows
          alias: githubwf
        - pkg: github.com/tzrikka/revchat/pkg/slack/activities
          alias: slack
        - pkg: github.com/tzrikka/revchat/pkg/slack/workflows
          alias: slackwf
        - pkg: github.com/tzrikka/thrippy-api/thrippy/v1
          alias: thrippypb
        - pkg: github.com/tzrikka/timpani-api/pkg/slack
          alias: tslack
        - pkg: github.com/urfave/cli-altsrc/v3
          alias: altsrc
        - pkg: go.opentelemetry.io/otel/metric
          alias: otelmetric
        - pkg: go.opentelemetry.io/otel/semconv/v1.37.0
          alias: semconv
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-explanation: true
    predeclared:
      qualified-name: true
    revive:
      enable-default-rules: true
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
    sloglint:
      attr-only: true
      key-naming-case: snake

formatters:
  enable:
    - gci
    - gofumpt
    - golines

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/tzrikka)
    gofumpt:
      extra-rules: true
    golines:
      max-len: 150

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
